#!/usr/bin/env bash

docker pull quay.io/biocontainers/samtools:1.3--1

docker run -it quay.io/biocontainers/samtools:1.3--1
    samtools --help
    exit

docker run -d quay.io/biocontainers/samtools:1.3--1 
docker ps
docker run -d quay.io/biocontainers/samtools:1.3--1 /bin/sh -c "while true; do sleep 1; done"
docker ps
docker stop ...
docker start ...
docker exec ... samtools --help

mkdir samtool_dir
wget https://raw.githubusercontent.com/samtools/samtools/develop/examples/toy.sam 
mv toy.sam samtool_dir
docker run -it -v $PWD/samtool_dir:/samtool_dir quay.io/biocontainers/samtools:1.3--1
    ls /samtool_dir/
    samtools view /samtool_dir/toy.sam
    samtools stats /samtool_dir/toy.sam > /samtool_dir/toy_stat